import { buildInvitationViewModel } from "../../invitation-rendering/build-invitation-view-model";
import { extractSnapshotMediaRefs } from "../../invitation-rendering/extract-snapshot-media-refs";
import type { GuestOverlay, MediaResolution, MediaResolver } from "../../invitation-rendering/invitation-view-model-types";
import type { RendererCompatibilityRegistry } from "../../invitation-rendering/renderer-registry";
import { selectRendererCompatibility } from "../../invitation-rendering/renderer-selection";
import { resolveSnapshotMedia } from "../../invitation-rendering/resolve-snapshot-media";
import { assertStoredReviewSnapshot } from "../invitation-review/assert-stored-review-snapshot";
import { PROJECT_MEDIA_BUCKET } from "../media/media-constants";
import type {
  PublicInvitationGateway,
  PublicInvitationView,
  PublishedInvitationMediaSigner,
  PublishedInvitationVersionRecord,
} from "./public-invitation-types";

export interface LoadPublicInvitationDependencies {
  invitations: PublicInvitationGateway;
  signMedia: PublishedInvitationMediaSigner;
  rendererRegistry: RendererCompatibilityRegistry;
}

/**
 * `project_invitations.public_slug` as generated by 0012
 * (`lower(project_code) || '-' || lower(variant)`): lowercase ASCII
 * alphanumerics separated by single hyphens. Anything else is not-found
 * without touching the database.
 */
const PUBLIC_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const PUBLIC_SLUG_MAX_LENGTH = 100;

export function isWellFormedPublicSlug(value: string): boolean {
  return value.length <= PUBLIC_SLUG_MAX_LENGTH && PUBLIC_SLUG_PATTERN.test(value);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Resolver over ONLY the PUBLISHED version's pinned media: a Snapshot ref
 * that is not pinned to this exact version, lives outside the approved
 * bucket, or could not be signed is UNAVAILABLE — never looked up elsewhere.
 */
function pinnedMediaResolver(
  version: PublishedInvitationVersionRecord,
  urls: ReadonlyMap<string, string>,
  refs: readonly string[],
): MediaResolver {
  const pinned = new Map(version.media.map((row) => [row.id, row]));
  const results = new Map<string, MediaResolution>();
  for (const mediaId of refs) {
    const row = pinned.get(mediaId);
    const url = urls.get(mediaId);
    results.set(
      mediaId,
      row !== undefined && row.storageBucket === PROJECT_MEDIA_BUCKET && url !== undefined
        ? { status: "RESOLVED", mediaId, url, width: row.width, height: row.height }
        : { status: "UNAVAILABLE", mediaId },
    );
  }
  return {
    async resolveMedia(mediaId: string): Promise<MediaResolution> {
      const result = results.get(mediaId);
      if (result === undefined) {
        throw new Error("Media resolver was asked for an id outside its preloaded set");
      }
      return result;
    },
  };
}

/**
 * Public invitation use case (Task 032A):
 *
 *   public slug → `get_public_invitation` (service_role RPC; exact
 *     `published_version_id` → PUBLISHED row of that invitation + Project,
 *     and only the media pinned to that version)
 *   → integrity gate on the persisted Snapshot (variant, template version,
 *     renderer key, Project code must equal the stored row binding)
 *   → PUBLISHED INVITATION MEDIA SIGNING ONLY for pinned refs the Snapshot uses
 *   → ViewModel + exact pinned renderer (fail closed, no fallback).
 *
 * `null` = unknown/malformed slug or never published (render not-found).
 * Any integrity or renderer fault throws. Never reads or rebuilds the
 * mutable draft, never falls back to REVIEW. Signed URLs exist only in the
 * returned ViewModel and are never persisted.
 *
 * `guest` (Task 033B1) is an ALREADY-AUTHORIZED overlay, supplied only by
 * the personalized loader after the guest token resolved on this slug;
 * omitted for the generic /i/[slug] flow, which is otherwise identical.
 */
export async function loadPublicInvitation(
  publicSlug: string,
  deps: LoadPublicInvitationDependencies,
  guest?: GuestOverlay,
): Promise<PublicInvitationView | null> {
  if (!isWellFormedPublicSlug(publicSlug)) {
    return null;
  }

  const record = await deps.invitations.getPublicInvitation(publicSlug);
  if (record === null) {
    return null;
  }
  const version = record.publishedVersion;

  const snapshot = assertStoredReviewSnapshot({
    variant: record.variant,
    templateVersionId: version.templateVersionId,
    rendererKey: version.rendererKey,
    payload: version.payload,
  });
  const payloadProject: unknown = (version.payload as Record<string, unknown>).project;
  if (!isRecord(payloadProject) || payloadProject.code !== record.projectCode) {
    throw new Error("Stored published Snapshot belongs to a different Project");
  }

  // Sign only pinned rows that the persisted Snapshot actually references.
  const refs = extractSnapshotMediaRefs(snapshot);
  const wanted = new Set(refs);
  const toSign = version.media
    .filter((row) => wanted.has(row.id) && row.storageBucket === PROJECT_MEDIA_BUCKET)
    .map((row) => ({ id: row.id, storagePath: row.storagePath }));
  const urls = toSign.length === 0 ? new Map<string, string>() : await deps.signMedia(toSign);

  const mediaResolutions = await resolveSnapshotMedia(snapshot, pinnedMediaResolver(version, urls, refs));
  const viewModel = buildInvitationViewModel(guest === undefined ? { snapshot, mediaResolutions } : { snapshot, guest, mediaResolutions });
  const selection = selectRendererCompatibility({ snapshot, viewModel, registry: deps.rendererRegistry });

  return { rendererKey: selection.rendererKey, viewModel, sections: selection.effectiveSections };
}
